### ISSUE TITLE
Clipboard example broken

### ISSUE THREAD

**Issue by jremb** [DioxusLabs/dioxus-std#28]
1. `dioxus_desktop::launch(app)` -> this refers to a module, not a callable function, can be fixed by replacing with `LaunchBuilder::desktop().launch(app)`
2. `e.data.value.clone()` -> value is a method and apparently should be `e.data.value().clone()`
3. `use_clipboard()` -> this requires an argument of type `&dioxus_core::scopes::ScopeState`
 
I don't know how to fix third issue. I'm not familiar with React-like designs (haven't had an HTML, CSS, JavaScript class since high school) and just wanted to try re-creating a simple app I have in Egui over to Dioxus after hearing about the latest update.

**Comment by DogeDark** [comment]
Dioxus-STD is still being migrated to version 0.5 and I estimate it'll be out sometime next week. Looks like parts of the clipboard example were missed during our migration though.
